version: '3.4'

services:
  classtranscribeserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44371
    stdin_open: true
    tty: true
    command: tail -f /dev/null