version: '3.4'

services:
  classtranscribeserver:
    image: ${DOCKER_REGISTRY-}classtranscribeserver
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./ClassTranscribeServer
        target: /ClassTranscribeServer
      - type: bind
        source: ./ClassTranscribeDatabase
        target: /ClassTranscribeDatabase
    container_name: "CTServer"
    ports:
        - "4443:443"
        - "8080:80"
    depends_on:
      - db
    env_file:
      - "ctserver-env.list"
    command: sh -c "dotnet build /ClassTranscribeServer/ClassTranscribeServer.csproj -c Release -o /app &&
                    dotnet /app/ClassTranscribeServer.dll"
  db:
    image: crunchydata/crunchy-postgres:centos7-10.4-2.0.0
    volumes:
      - "pgvolume:/pgdata"
    env_file:
      - "pg-env.list"
    ports:
      - "5432:5432"
    container_name: "CT2019db"

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - "5050:80"
    volumes:
      - "pga4volume:/var/lib/pgadmin"
    env_file:
      - "pgadmin-env.list"
    container_name: "pgadmin"
    
volumes:
  pga4volume:
  pgvolume: