version: '3.4'

services:
  classtranscribeserver:
    command: sh -c "chmod a+x launchscript.sh; ./launchscript.sh"
  rpcserver:
    command: sh -c "cd NodeRpcServer; npm install; npm rebuild; npm start"