version: '3.4'

services:
  classtranscribeserver:
    image: ${DOCKER_REGISTRY-}classtranscribeserver
    build:
      context: .
      dockerfile: ASP.Dockerfile
    volumes:
      - type: bind
        source: ./ClassTranscribeServer
        target: /ClassTranscribeServer
      - type: bind
        source: ./ClassTranscribeDatabase
        target: /ClassTranscribeDatabase
      - type: bind
        source: ./TaskEngine
        target: /TaskEngine
      - type: bind
        source: ./Data
        target: /Data
      - type: bind
        source: ./vs_appsettings.json
        target: /vs_appsettings.json
      - type: bind
        source: ./ct.proto
        target: /ct.proto
      - type: bind
        source: ./launchscript.sh
        target: /launchscript.sh
    container_name: "CTServer"
    ports:
        - "6060:6060"
        - "6061:6061"
    depends_on:
      - db
      - rabbit
      - rpcserver
    env_file:
      - "ctserver-env.list"    
  db:
    image: crunchydata/crunchy-postgres:centos7-10.4-2.0.0
    volumes:
      - "pgvolume:/pgdata" 
    env_file:
      - "ctserver-env.list"
    ports:
      - "5432:5432"
    container_name: "CT2019db"

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - "5050:80"
    volumes:
      - "pga4volume:/var/lib/pgadmin"
    env_file:
      - "ctserver-env.list"
    container_name: "pgadmin"
  
  rabbit:
    image: rabbitmq:management
    container_name: rabbit
    env_file:
      - "ctserver-env.list"
    ports:
      - "15671-15672:15671-15672"
      - "4369:4369"
      - "25672:25672"
      - "5671-5672:5671-5672"
    
  rpcserver:
    image: ${DOCKER_REGISTRY-}rpcserver
    build:
      context: .
      dockerfile: rpcserver.Dockerfile
    env_file:
      - "ctserver-env.list"
    volumes:
        - type: bind
          source: ./NodeRpcServer
          target: /NodeRpcServer
        - type: bind
          source: ./Data
          target: /Data
        - type: bind
          source: ./ct.proto  
          target: /NodeRpcServer/ct.proto
        - /NodeRpcServer/node_modules
    ports:
      - "50052:50052"
  nginx:
    # Inspired from https://dev.to/herocod3r/configuring-ssl-on-an-aspnet-core-docker-container-1c9l
    image: nginx:1.15-alpine
    ports:
      - "4442:4442"
      - "4443:4443"
    depends_on:
      - classtranscribeserver
    env_file:
      ctserver-env.list
    volumes:
      - ./nginx:/etc/nginx/conf.d
      # Replace with appropriate directory
      - /home/mahipal2/FrontEnd/certbot/conf:/etc/letsencrypt
      - /home/mahipal2/FrontEnd/certbot/www:/var/www/certbot
    # envsubst replaces environment variables in app.conf.template with the actual values to generate app.conf
    command: /bin/sh -c "envsubst < /etc/nginx/conf.d/app.conf.template > /etc/nginx/conf.d/app.conf && exec nginx -g 'daemon off;'"
    links:
      - classtranscribeserver
volumes:
  pga4volume:
  pgvolume: