name: Docker Image CI

on:
  push:
    branches: 
      - master

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file TaskEngine.Dockerfile --tag classtranscribe/taskengine:latest
      #run: docker push classtranscribe/taskengine:latest
